const toggle=document.querySelector('#menu-toggle');
const menu=document.querySelector('#mobile-menu');
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.setAttribute('aria-label',open?'Открыть меню':'Закрыть меню');menu.hidden=open;});
menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Открыть меню');}));
const form=document.querySelector('#booking-form');
const date=form.elements.date;
const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;date.min=today;
document.querySelectorAll('[data-service]').forEach(el=>el.addEventListener('click',()=>{form.elements.service.value=el.dataset.service;document.querySelector('#booking').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}));
document.querySelectorAll('[data-master]').forEach(el=>el.addEventListener('click',()=>{form.elements.master.value=el.dataset.master;}));
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;document.querySelector('#form-result').textContent=`${form.elements.name.value.trim()}, всё заполнено: ${form.elements.service.value}, ${date.value.split('-').reverse().join('.')}. Это демонстрация — запись не создана и данные не отправлены.`;});
form.addEventListener('input',()=>{document.querySelector('#form-result').textContent='';});
