import js from '@eslint/js';
import globals from 'globals';

/**
 * Root ESLint flat config.
 *
 * This is intentionally minimal for the workspace scaffold (Step 1). Package-
 * specific configs (Astro, Payload/Next, TypeScript type-aware rules) are added
 * per package via `@treenweb/eslint-config` in later steps.
 */
export default [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.astro/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/.output/**',
      '**/coverage/**',
      '**/playwright-report/**',
      '**/test-results/**',
      '**/.lighthouseci/**',
      // generated by Payload
      '**/payload-types.ts',
      '**/importMap.js',
      '**/.next/**',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.node },
    },
  },
];
