/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'card-packs': CardPack;
    cards: Card;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'card-packs': CardPacksSelect<false> | CardPacksSelect<true>;
    cards: CardsSelect<false> | CardsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('cs' | 'en' | 'ru') | ('cs' | 'en' | 'ru')[];
  globals: {
    'site-settings': SiteSetting;
    'vesco-navigation': VescoNavigation;
    'vesco-hero': VescoHero;
    'vesco-counters': VescoCounter;
    'vesco-cta': VescoCta;
    'vesco-footer': VescoFooter;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'vesco-navigation': VescoNavigationSelect<false> | VescoNavigationSelect<true>;
    'vesco-hero': VescoHeroSelect<false> | VescoHeroSelect<true>;
    'vesco-counters': VescoCountersSelect<false> | VescoCountersSelect<true>;
    'vesco-cta': VescoCtaSelect<false> | VescoCtaSelect<true>;
    'vesco-footer': VescoFooterSelect<false> | VescoFooterSelect<true>;
  };
  locale: 'cs' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Required in the default locale; fill each locale for a11y.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "card-packs".
 */
export interface CardPack {
  id: number;
  name: string;
  /**
   * URL-safe identifier, e.g. "classic-tarot". Not localized.
   */
  slug: string;
  coverImage?: (number | null) | Media;
  description?: string | null;
  /**
   * Bump when cards change meaningfully — the frontend cache compares this to decide whether to refetch.
   */
  version?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cards".
 */
export interface Card {
  id: number;
  /**
   * The pack this card belongs to.
   */
  pack: number | CardPack;
  name: string;
  image: number | Media;
  meaningUpright?: string | null;
  meaningReversed?: string | null;
  /**
   * Display order within the pack.
   */
  order?: number | null;
  /**
   * e.g. major-arcana, cups, fire — free-form, not a fixed enum.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'card-packs';
        value: number | CardPack;
      } | null)
    | ({
        relationTo: 'cards';
        value: number | Card;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "card-packs_select".
 */
export interface CardPacksSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  coverImage?: T;
  description?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cards_select".
 */
export interface CardsSelect<T extends boolean = true> {
  pack?: T;
  name?: T;
  image?: T;
  meaningUpright?: T;
  meaningReversed?: T;
  order?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  description?: string | null;
  ogImage?: (number | null) | Media;
  seo?: {
    /**
     * Tokens: {page} {site}. e.g. "{page} · {site}". Blank keeps the default "{page} · {site}".
     */
    titleTemplate?: string | null;
    /**
     * Meta description for pages that have none of their own. Blank falls back to “Description” above.
     */
    defaultDescription?: string | null;
  };
  /**
   * Social links shown as icons in the footer.
   */
  social?:
    | {
        /**
         * instagram, facebook, tiktok, youtube, telegram, whatsapp, x, linkedin. Aliases: twitter→x, fb, ig, yt, tg, wa. Anything else gets a generic link icon.
         */
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  ticker?:
    | {
        word: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    address?: string | null;
    phone?: string | null;
    hoursWeekday?: string | null;
    hoursSaturday?: string | null;
    hoursSunday?: string | null;
    mapUrl?: string | null;
  };
  /**
   * Small print in the footer bar.
   */
  footerNote?: string | null;
  /**
   * Entrance animation for the home hero. Same for every locale.
   */
  heroAnimation?: ('fade' | 'slide-up' | 'zoom' | 'neon') | null;
  /**
   * Landing redirect for "/" and the hreflang x-default target. Must be one of the enabled locales below. The fallback language for untranslated fields is fixed in code (ru) and is not affected by this.
   */
  defaultLocale: 'cs' | 'en' | 'ru';
  /**
   * Locales offered in the switcher / hreflang. Codes must match localization.locales in payload.config.ts.
   */
  supportedLocales?:
    | {
        code: string;
        label: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-navigation".
 */
export interface VescoNavigation {
  id: number;
  /**
   * "est. mmxxvi" tagline next to the logo.
   */
  estLabel?: string | null;
  pullCardLabel?: string | null;
  nav?: {
    home?: string | null;
    tarot?: string | null;
    horoscope?: string | null;
    numerology?: string | null;
    dashboard?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-hero".
 */
export interface VescoHero {
  id: number;
  eyebrow?: string | null;
  headingLine1?: string | null;
  headingLine2?: string | null;
  headingAccent?: string | null;
  /**
   * The intro / description paragraph under the heading.
   */
  lede?: string | null;
  ctaBeginLabel?: string | null;
  ctaNumbersLabel?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-counters".
 */
export interface VescoCounter {
  id: number;
  /**
   * Caption under "78".
   */
  cardsLabel?: string | null;
  /**
   * Caption under "12".
   */
  signsLabel?: string | null;
  /**
   * Caption under "6".
   */
  numbersLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-cta".
 */
export interface VescoCta {
  id: number;
  headingLine1?: string | null;
  headingLine2?: string | null;
  body?: string | null;
  /**
   * "day streak" caption.
   */
  dayStreakLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-footer".
 */
export interface VescoFooter {
  id: number;
  /**
   * "Variant I · Mystic Minimalism".
   */
  tagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  ogImage?: T;
  seo?:
    | T
    | {
        titleTemplate?: T;
        defaultDescription?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  ticker?:
    | T
    | {
        word?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        hoursWeekday?: T;
        hoursSaturday?: T;
        hoursSunday?: T;
        mapUrl?: T;
      };
  footerNote?: T;
  heroAnimation?: T;
  defaultLocale?: T;
  supportedLocales?:
    | T
    | {
        code?: T;
        label?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-navigation_select".
 */
export interface VescoNavigationSelect<T extends boolean = true> {
  estLabel?: T;
  pullCardLabel?: T;
  nav?:
    | T
    | {
        home?: T;
        tarot?: T;
        horoscope?: T;
        numerology?: T;
        dashboard?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-hero_select".
 */
export interface VescoHeroSelect<T extends boolean = true> {
  eyebrow?: T;
  headingLine1?: T;
  headingLine2?: T;
  headingAccent?: T;
  lede?: T;
  ctaBeginLabel?: T;
  ctaNumbersLabel?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-counters_select".
 */
export interface VescoCountersSelect<T extends boolean = true> {
  cardsLabel?: T;
  signsLabel?: T;
  numbersLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-cta_select".
 */
export interface VescoCtaSelect<T extends boolean = true> {
  headingLine1?: T;
  headingLine2?: T;
  body?: T;
  dayStreakLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vesco-footer_select".
 */
export interface VescoFooterSelect<T extends boolean = true> {
  tagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}