/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    masters: Master;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    masters: MastersSelect<false> | MastersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('cs' | 'en' | 'ru') | ('cs' | 'en' | 'ru')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'ui-labels': UiLabel;
    hero: Hero;
    services: Service;
    about: About;
    team: Team;
    booking: Booking;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'ui-labels': UiLabelsSelect<false> | UiLabelsSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    booking: BookingSelect<false> | BookingSelect<true>;
  };
  locale: 'cs' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment. Generated from the title if left blank.
   */
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * Overrides <title> / OG title. Falls back to the document title.
     */
    title?: string | null;
    /**
     * Meta description / OG description (~155 chars).
     */
    description?: string | null;
    /**
     * OG / social share image. Shared across locales.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Required in the default locale; fill each locale for a11y.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL path segment. Generated from the title if left blank.
   */
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Overrides <title> / OG title. Falls back to the document title.
     */
    title?: string | null;
    /**
     * Meta description / OG description (~155 chars).
     */
    description?: string | null;
    /**
     * OG / social share image. Shared across locales.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "masters".
 */
export interface Master {
  id: number;
  name: string;
  /**
   * e.g. "АЛ".
   */
  initials: string;
  specialty?: string | null;
  /**
   * Link text, e.g. "Записаться к Алексу ↗".
   */
  bookingLabel?: string | null;
  photo?: (number | null) | Media;
  /**
   * Ascending. Ties break by creation order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Path to match, e.g. /old-page
   */
  from: string;
  /**
   * Destination path or absolute URL
   */
  to: string;
  /**
   * On = 308 permanent. Off = 307 temporary.
   */
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'masters';
        value: number | Master;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "masters_select".
 */
export interface MastersSelect<T extends boolean = true> {
  name?: T;
  initials?: T;
  specialty?: T;
  bookingLabel?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  description?: string | null;
  ogImage?: (number | null) | Media;
  seo?: {
    /**
     * Tokens: {page} {site}. e.g. "{page} · {site}". Blank keeps the default "{page} · {site}".
     */
    titleTemplate?: string | null;
    /**
     * Meta description for pages that have none of their own. Blank falls back to “Description” above.
     */
    defaultDescription?: string | null;
  };
  social?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  ticker?:
    | {
        word: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    address?: string | null;
    phone?: string | null;
    hoursWeekday?: string | null;
    hoursSaturday?: string | null;
    hoursSunday?: string | null;
    mapUrl?: string | null;
  };
  /**
   * Small print in the footer bar.
   */
  footerNote?: string | null;
  /**
   * Entrance animation for the home hero. Same for every locale.
   */
  heroAnimation?: ('fade' | 'slide-up' | 'zoom' | 'neon') | null;
  /**
   * Landing redirect for "/" and the hreflang x-default target. Must be one of the enabled locales below. The fallback language for untranslated fields is fixed in code (ru) and is not affected by this.
   */
  defaultLocale: 'cs' | 'en' | 'ru';
  /**
   * Locales offered in the switcher / hreflang. Codes must match localization.locales in payload.config.ts.
   */
  supportedLocales?:
    | {
        code: string;
        label: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  main?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide interface wording. A blank field falls back to the built-in translation for that locale.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-labels".
 */
export interface UiLabel {
  id: number;
  header?: {
    /**
     * Header “Book” button.
     */
    cta?: string | null;
  };
  footer?: {
    findUsHeading?: string | null;
    hoursHeading?: string | null;
    disclaimer?: string | null;
  };
  booking?: {
    nameLabel?: string | null;
    namePlaceholder?: string | null;
    phoneLabel?: string | null;
    phonePlaceholder?: string | null;
    serviceLabel?: string | null;
    masterLabel?: string | null;
    anyMasterOption?: string | null;
    dateLabel?: string | null;
    submitLabel?: string | null;
    /**
     * Confirmation line. Tokens: {name} {service} {date}.
     */
    resultTemplate?: string | null;
  };
  notFound?: {
    /**
     * <title> for a missing content page.
     */
    pageMetaTitle?: string | null;
    /**
     * <title> for a missing post.
     */
    postMetaTitle?: string | null;
    /**
     * On-page heading for a missing content page.
     */
    heading?: string | null;
    /**
     * Heading for the standalone /404 route.
     */
    heading404?: string | null;
    /**
     * Body text on the standalone /404 route.
     */
    body?: string | null;
    /**
     * Missing-page line. Token: {path} (rendered in <code>).
     */
    missingPathTemplate?: string | null;
    /**
     * On-page heading for a missing post.
     */
    postHeading?: string | null;
    /**
     * “Back to home” link text.
     */
    backHomeLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  eyebrowLeft?: string | null;
  eyebrowRight?: string | null;
  headingLine1?: string | null;
  /**
   * Second line, rendered in the accent colour.
   */
  headingAccent?: string | null;
  introText?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  sealText?: string | null;
  sealCaption?: string | null;
  photo?: (number | null) | Media;
  photoCaptionLeft?: string | null;
  photoCaptionRight?: string | null;
  /**
   * Corner rounding for this section’s buttons, cards and form fields.
   */
  rounded?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  /**
   * Corner rounding for the hero photo only.
   */
  photoRounded?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * e.g. "01 / УСЛУГИ".
   */
  eyebrow?: string | null;
  /**
   * Headline. Line breaks are preserved on the site.
   */
  heading?: string | null;
  /**
   * Optional trailing fragment rendered in the accent colour.
   */
  headingAccent?: string | null;
  /**
   * Optional muted text beside the headline.
   */
  note?: string | null;
  /**
   * Rendered in this order.
   */
  items?:
    | {
        name: string;
        /**
         * Optional pill, e.g. "КОМБО".
         */
        badge?: string | null;
        description?: string | null;
        /**
         * e.g. "60 мин".
         */
        duration?: string | null;
        priceAmount?: number | null;
        priceCurrency?: string | null;
        /**
         * Optional #id link target.
         */
        anchor?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Corner rounding for this section’s buttons, cards and form fields.
   */
  rounded?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * e.g. "01 / УСЛУГИ".
   */
  eyebrow?: string | null;
  /**
   * Headline. Line breaks are preserved on the site.
   */
  heading?: string | null;
  /**
   * Optional trailing fragment rendered in the accent colour.
   */
  headingAccent?: string | null;
  /**
   * Optional muted text beside the headline.
   */
  note?: string | null;
  leadParagraph?: string | null;
  bodyParagraph?: string | null;
  footnote?: string | null;
  /**
   * Corner rounding for this section’s buttons, cards and form fields.
   */
  rounded?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  /**
   * e.g. "01 / УСЛУГИ".
   */
  eyebrow?: string | null;
  /**
   * Headline. Line breaks are preserved on the site.
   */
  heading?: string | null;
  /**
   * Optional trailing fragment rendered in the accent colour.
   */
  headingAccent?: string | null;
  /**
   * Optional muted text beside the headline.
   */
  note?: string | null;
  /**
   * Corner rounding for this section’s buttons, cards and form fields.
   */
  rounded?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking".
 */
export interface Booking {
  id: number;
  /**
   * e.g. "01 / УСЛУГИ".
   */
  eyebrow?: string | null;
  /**
   * Headline. Line breaks are preserved on the site.
   */
  heading?: string | null;
  /**
   * Optional trailing fragment rendered in the accent colour.
   */
  headingAccent?: string | null;
  /**
   * Optional muted text beside the headline.
   */
  note?: string | null;
  intro?: string | null;
  /**
   * Notice shown under the demo form.
   */
  disclaimer?: string | null;
  /**
   * Corner rounding for this section’s buttons, cards and form fields.
   */
  rounded?: ('none' | 'sm' | 'md' | 'lg' | 'full') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  ogImage?: T;
  seo?:
    | T
    | {
        titleTemplate?: T;
        defaultDescription?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  ticker?:
    | T
    | {
        word?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        hoursWeekday?: T;
        hoursSaturday?: T;
        hoursSunday?: T;
        mapUrl?: T;
      };
  footerNote?: T;
  heroAnimation?: T;
  defaultLocale?: T;
  supportedLocales?:
    | T
    | {
        code?: T;
        label?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  main?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-labels_select".
 */
export interface UiLabelsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        cta?: T;
      };
  footer?:
    | T
    | {
        findUsHeading?: T;
        hoursHeading?: T;
        disclaimer?: T;
      };
  booking?:
    | T
    | {
        nameLabel?: T;
        namePlaceholder?: T;
        phoneLabel?: T;
        phonePlaceholder?: T;
        serviceLabel?: T;
        masterLabel?: T;
        anyMasterOption?: T;
        dateLabel?: T;
        submitLabel?: T;
        resultTemplate?: T;
      };
  notFound?:
    | T
    | {
        pageMetaTitle?: T;
        postMetaTitle?: T;
        heading?: T;
        heading404?: T;
        body?: T;
        missingPathTemplate?: T;
        postHeading?: T;
        backHomeLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  eyebrowLeft?: T;
  eyebrowRight?: T;
  headingLine1?: T;
  headingAccent?: T;
  introText?: T;
  ctaLabel?: T;
  ctaHref?: T;
  sealText?: T;
  sealCaption?: T;
  photo?: T;
  photoCaptionLeft?: T;
  photoCaptionRight?: T;
  rounded?: T;
  photoRounded?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  note?: T;
  items?:
    | T
    | {
        name?: T;
        badge?: T;
        description?: T;
        duration?: T;
        priceAmount?: T;
        priceCurrency?: T;
        anchor?: T;
        id?: T;
      };
  rounded?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  note?: T;
  leadParagraph?: T;
  bodyParagraph?: T;
  footnote?: T;
  rounded?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  note?: T;
  rounded?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking_select".
 */
export interface BookingSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  note?: T;
  intro?: T;
  disclaimer?: T;
  rounded?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}