import type { FormaContent } from './types';

export const formaCs: FormaContent = {
  nav: [
    { label: 'O nás', href: '#about' },
    { label: 'Služby a ceny', href: '#services' },
    { label: 'Holiči', href: '#team' },
    { label: 'Kontakty', href: '#contacts' },
  ],
  ticker: ['STŘIH', 'VOUSY', 'CHARAKTER'],
  hero: {
    eyebrowLeft: 'BARBERSHOP · MUŽSKÉ ÚZEMÍ',
    eyebrowRight: 'STYL ZAČÍNÁ U DETAILŮ',
    headingLine1: 'TVŮJ TVAR.',
    headingAccent: 'TVŮJ CHARAKTER.',
    introText: 'Přesný střih. Čisté linie.\nNic navíc — jen to, co ti sedí.',
    ctaLabel: 'Vybrat čas',
    ctaHref: '#booking',
    sealText: 'F.',
    sealCaption: 'Klasické techniky. Moderní pohled.',
    photo: null,
    photoCaptionLeft: 'ŘEMESLO V KAŽDÉM POHYBU',
    photoCaptionRight: '01 / FORMA',
  },
  heroPhotoAlt: 'Holič tvaruje pánský střih nůžkami a hřebenem',
  services: {
    eyebrow: '01 / SLUŽBY',
    heading: 'DOBRÝ TVAR.\nFÉROVÁ CENA.',
    headingAccent: null,
    note: 'Zůstaň u osvědčeného, nebo zkus něco nového. S tvarem ti poradíme.',
    items: [
      {
        name: 'Pánský střih',
        description: 'Konzultace, mytí a styling',
        duration: '60 min',
        priceAmount: 600,
        priceCurrency: 'Kč',
      },
      {
        name: 'Vousy a knír',
        description: 'Modelace tvaru a čistý kontur',
        duration: '30 min',
        priceAmount: 350,
        priceCurrency: 'Kč',
      },
      {
        name: 'Střih + vousy',
        badge: 'KOMBO',
        description: 'Kompletní vzhled na jednu návštěvu',
        duration: '90 min',
        priceAmount: 850,
        priceCurrency: 'Kč',
      },
      {
        name: 'Klasické holení',
        description: 'Horký ručník a péče o pleť',
        duration: '45 min',
        priceAmount: 450,
        priceCurrency: 'Kč',
      },
    ],
  },
  about: {
    eyebrow: '02 / FILOZOFIE',
    heading: 'MÍSTO, KDE\nMŮŽEŠ BÝT\nSÁM SEBOU.',
    headingAccent: null,
    note: null,
    leadParagraph:
      'Nestříháme všechny stejně. Díváme se na tvar obličeje, růst vlasů i tvůj životní rytmus. A pak se pustíme do práce.',
    bodyParagraph:
      'Můžeš probrat fotbal, nebo prostě mlčet. Dobrá hudba, šálek kávy a čas pro sebe jsou v ceně.',
    footnote: 'DŮRAZ NA DETAIL. RESPEKT K TOBĚ.',
  },
  team: {
    eyebrow: '03 / TÝM',
    heading: 'ZNEJ SVÉHO\nHOLIČE.',
    headingAccent: null,
    note: 'Různé povahy. Jeden přístup ke kvalitě.',
  },
  masters: [
    {
      id: 'fb-1',
      initials: 'АЛ',
      name: 'Alex',
      specialty: 'Klasika a střihy nůžkami',
      bookingLabel: 'Objednat k Alexovi ↗',
      order: 1,
    },
    {
      id: 'fb-2',
      initials: 'МР',
      name: 'Marek',
      specialty: 'Fady a moderní tvary',
      bookingLabel: 'Objednat k Markovi ↗',
      order: 2,
    },
    {
      id: 'fb-3',
      initials: 'ДН',
      name: 'Dan',
      specialty: 'Modelace vousů a holení',
      bookingLabel: 'Objednat k Danovi ↗',
      order: 3,
    },
  ],
  booking: {
    eyebrow: '04 / OBJEDNÁNÍ',
    heading: 'ČAS NA\nNOVÝ',
    headingAccent: 'TVAR.',
    note: null,
    intro: 'Vyber si službu a termín, který ti vyhovuje.',
    disclaimer: 'Ukázkový formulář: nic se neodesílá a žádný termín se nerezervuje.',
  },
  site: {
    siteName: 'FORMA',
    tagline: 'Tvůj tvar. Tvůj charakter.',
    description: 'FORMA — pánské střihy, úprava vousů a klasické holení. Najdi svůj tvar.',
    footerNote: '© 2026 FORMA. Ukázková šablona.',
    contact: {
      address: 'Plzeň, adresa barbershopu',
      phone: '',
      hoursWeekday: 'Po–Pá · 10:00–20:00',
      hoursSaturday: 'So · 10:00–18:00',
      hoursSunday: 'Ne · zavřeno',
      mapUrl: '',
    },
  },
};
