import type { FormaContent } from './types';

export const formaEn: FormaContent = {
  nav: [
    { label: 'About', href: '#about' },
    { label: 'Services & prices', href: '#services' },
    { label: 'Barbers', href: '#team' },
    { label: 'Contacts', href: '#contacts' },
  ],
  ticker: ['HAIRCUT', 'BEARD', 'CHARACTER'],
  hero: {
    eyebrowLeft: "BARBERSHOP · MEN'S TERRITORY",
    eyebrowRight: 'STYLE STARTS WITH THE DETAILS',
    headingLine1: 'YOUR SHAPE.',
    headingAccent: 'YOUR CHARACTER.',
    introText: 'A precise cut. Clean lines.\nNothing extra — just what suits you.',
    ctaLabel: 'Pick a time',
    ctaHref: '#booking',
    sealText: 'F.',
    sealCaption: 'Classic technique. Modern eye.',
    photo: null,
    photoCaptionLeft: 'CRAFT IN EVERY MOVE',
    photoCaptionRight: '01 / FORMA',
  },
  heroPhotoAlt: "A barber shaping a men's haircut with scissors and comb",
  services: {
    eyebrow: '01 / SERVICES',
    heading: 'GOOD SHAPE.\nFAIR PRICE.',
    headingAccent: null,
    note: "Stick with the familiar or try something new. We'll help you find your shape.",
    items: [
      {
        name: "Men's haircut",
        description: 'Consultation, wash and styling',
        duration: '60 min',
        priceAmount: 600,
        priceCurrency: 'Kč',
      },
      {
        name: 'Beard & moustache',
        description: 'Shaping and a clean outline',
        duration: '30 min',
        priceAmount: 350,
        priceCurrency: 'Kč',
      },
      {
        name: 'Haircut + beard',
        badge: 'COMBO',
        description: 'The full look in one visit',
        duration: '90 min',
        priceAmount: 850,
        priceCurrency: 'Kč',
      },
      {
        name: 'Classic shave',
        description: 'Hot towel and skin care',
        duration: '45 min',
        priceAmount: 450,
        priceCurrency: 'Kč',
      },
    ],
  },
  about: {
    eyebrow: '02 / PHILOSOPHY',
    heading: 'A PLACE TO\nBE\nYOURSELF.',
    headingAccent: null,
    note: null,
    leadParagraph:
      "We don't cut everyone the same. We look at the shape of your face, how your hair grows and the rhythm of your life. Then we get to work.",
    bodyParagraph:
      'Talk football if you like, or just sit in silence. Good music, a cup of coffee and time for yourself are included.',
    footnote: 'ATTENTION TO DETAIL. RESPECT FOR YOU.',
  },
  team: {
    eyebrow: '03 / TEAM',
    heading: 'KNOW YOUR\nBARBER.',
    headingAccent: null,
    note: 'Different characters. One standard of quality.',
  },
  masters: [
    {
      id: 'fb-1',
      initials: 'АЛ',
      name: 'Alex',
      specialty: 'Classic cuts and scissor work',
      bookingLabel: 'Book with Alex ↗',
      order: 1,
    },
    {
      id: 'fb-2',
      initials: 'МР',
      name: 'Mark',
      specialty: 'Fades and modern shapes',
      bookingLabel: 'Book with Mark ↗',
      order: 2,
    },
    {
      id: 'fb-3',
      initials: 'ДН',
      name: 'Dan',
      specialty: 'Beard sculpting and shaves',
      bookingLabel: 'Book with Dan ↗',
      order: 3,
    },
  ],
  booking: {
    eyebrow: '04 / BOOKING',
    heading: 'TIME TO\nRESHAPE',
    headingAccent: 'YOUR SHAPE.',
    note: null,
    intro: 'Choose a service and a date that works.',
    disclaimer: 'Demo form: nothing is sent and no slot is booked.',
  },
  site: {
    siteName: 'FORMA',
    tagline: 'Your shape. Your character.',
    description: "FORMA — men's haircuts, beard grooming and classic shaves. Find your shape.",
    footerNote: '© 2026 FORMA. Demo template.',
    contact: {
      address: 'Pilsen, barbershop address',
      phone: '',
      hoursWeekday: 'Mon–Fri · 10:00–20:00',
      hoursSaturday: 'Sat · 10:00–18:00',
      hoursSunday: 'Sun · closed',
      mapUrl: '',
    },
  },
};
